### ISSUE TITLE
Getting Error 400 Client Error Bad request.

### ISSUE THREAD

**Issue by manish2409** [czpython/python-amazon-mws#30]
Hi I am using your code to access my amazon mws account.

import mws
auth = mws.Orders(access_key=my_access_key, secret_key=my_secret_key, account_id=my_account_id, region='IN')
auth.list_orders(marketplaceids, created_after='2015-06-01', created_before=None, lastupdatedafter=None, lastupdatedbefore=None, orderstatus=(), fulfillment_channels=(), payment_methods=(), buyer_email=None, seller_orderid=None, max_results='100')\

On executing this code i get this error:
mws.mws.MWSError: 400 Client Error: Bad Request

Please help.

Also on other methods like get_service_status()
It is returning data in form  mws.mws.DictWrapper object at 0x7fcc0a27e9d0
how do i Parse this type of data?

**Comment by GriceTurrble** [comment]
Ensure that your request works using the MWS Scratchpad, especially your credentials: https://mws.amazonservices.in/scratchpad/index.html (this link for IN region)

Aside from checking your credentials with the above link, I would ensure that `marketplaceids` contains the right data: http://docs.developer.amazonservices.com/en_US/orders/2013-09-01/Orders_ListOrders.html

----

As for the last part, all responses come back as XML converted into a Python object, with each key in the XML structure accessible as either dict keys or class attributes. If you do `response = auth.get_service_status()`, you can see the parsed data at `response.parsed`.

**Comment by manish2409** [comment]
I checked the scratchpad link and my credentials are working Ok. It returned orders in xml format.
Also I checked get_service_status() method. It returned me this string:

{'Status': {'value': 'GREEN'}, 'Timestamp': {'value': '2015-06-04T05:53:20.344Z'}, 'value': '\n    '}

I double checked all the credentials in my code and edited the 3rd line to:

auth.list_orders(marketplaceids='A21TJRUUN4KGV', ....  this is markertplace id for india region.

 but still giving me this 400 error.

**Comment by manish2409** [comment]
If it is possible for you can you give me an example on how to download order using list_orders by giving an example in python? I tried everything i could but no solution so far.
Please if you can help.

**Comment by GriceTurrble** [comment]
Shot in the dark, but `marketplaceids` is expecting a list. Try `['A21TJRUUN4KGV',]` instead.

**Comment by manish2409** [comment]
Hi Thanks you solved my problem.
Can you solve 1 last problem?
I have a bunch of amazon_order_ids.
I was using list_order_items() method inside a for loop and passing the order_ids from list but after some requests it started throwing max limit reached error.
Is there any way to pass a list of amazon_order_ids to list_order_items method so that it fetch data in a single request?

**Comment by GriceTurrble** [comment]
Unfortunately no, Amazon does not provide that type of functionality.

If the number of orders is relatively low, you can build in some throttle handling. Otherwise, you might try your luck with the Reports API: http://docs.developer.amazonservices.com/en_US/reports/Reports_Overview.html

**Comment by ironstove** [comment]
@GriceTurrble I ran into the same issue above and changing the marketplaceids to a list worked. Thanks for the help.

How were you able to recognize that the marketplaceids variable should be a list instead of a string?

I am working my way through the code and trying to better understand it. I see that the response of list_orders goes to the Orders class and the response is stored in Orders.original for xml, as far as I can see, there is no variable that stores the response as a flat file, so would it be alright if I were to create this functionality and make a pull request?

**Comment by GriceTurrble** [comment]
According to the [API reference for ListOrders](http://docs.developer.amazonservices.com/en_US/orders/2013-09-01/Orders_ListOrders.html), `MarketplaceId` is expected to be a list. The example request in the reference shows that this is given by the parameter `MarketplaceId.Id.`, followed by a number. So for multiple IDs, this would be `MarketplaceId.Id.1=FOO`, `MarketplaceId.Id.2=BAR`, etc.

In the package code for the ListOrders method [here](https://github.com/czpython/python-amazon-mws/blob/master/mws/mws.py#L418) *(disclaimer: not my code :) )*, MarketplaceId is handled by a method called `enumerate_params`, defined [here](https://github.com/czpython/python-amazon-mws/blob/master/mws/mws.py#L236). When you pass this method a string like `MarketplaceId.Id.` and a list of values, it will return the values of that list with the appropriate enumerated parameter in front of it.

The same is true in that same API call for Status, FulfillmentChannel, and PaymentMethod, but these may not be necessary. `enumerate_params` returns an empty dict if the list of parameters is empty, so that the parameter itself is completely omitted from the request.

---

> as far as I can see, there is no variable that stores the response as a flat file, so would it be alright if I were to create this functionality and make a pull request?

This is not necessary. In fact, the original XML response is given in a single string already. If you stored the response from an API call in an object like `response`, that can be accessed from `response.original`. You can then store the output of that long string to a file, if you want.

`original` is defined in the DictWrapper class, [here](https://github.com/czpython/python-amazon-mws/blob/master/mws/mws.py#L87). This is the class you typically work with when you get responses.

I have a Django site and PostGreSQL database running my requests, so I store the originals in a TextField. I also added a property to the DictWrapper class called `metadata`, which returns `self._response_dict.get('ResponseMetadata')`, and from here I typically grab the `response.metadata.RequestId` when I store a request (RequestId is not accessible from the `parsed` property in most cases).

**Comment by manish2409** [comment]
close
